### ISSUE TITLE
Quick Start Guide issues

### ISSUE THREAD

**Issue by oj-amazing** [chipsalliance/tools-cocotb-verilator-build#4]
(Copied from antmicro/cocotb-verilator-build#2)

Hitting some bumps when setting up my environment.

1. `env/bin/verilator` does not exist by default. Is this expected? I had to install Verilator using `sudo apt-get install verilator` instead.

2. `make env/bin/cocotb-config` run to completion, but running `./cocotb-config` results in an error message: `cocotb-config: command not found`. Even doing `pip install cocotb` results in the same issue. Am I missing a package or dependency?

**Comment by xiajenny** [comment]
1. `make env/bin/verilator` is a target in the Makefile in the root directory, did you run it from the right place? See this [line](https://github.com/chipsalliance/tools-cocotb-verilator-build/blob/master/Makefile#L35).
2. Similarly, `env/bin/cocotb-config` is a target in the Makefile, not a file itself.

The quickstart guide worked perfectly for me on macOS Mojave :)

**Comment by ZvonimirBandic** [comment]
oj-amazing: have you been able to resolve the issues? If make env/bin/cocotb-config ran to completion, this is good. Did you try running any examples? Also, make sure you are using python3-dev, i have had some issues with that.

**Comment by ZvonimirBandic** [comment]
Close
